name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello goodbye"
      - name: Print goodbaye
        run: echo "Done - bye!"
